# -*- coding: utf-8 -*-
"""RealActivity1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j1OKGfwOjAwutmD_xIKMVB4T4rXFwITs
"""

import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

ls 'drive/MyDrive/Colab Notebooks'

df = pd.read_csv('drive/MyDrive/Colab Notebooks/Loan_data.csv')
df

df.head()

df.tail()

df.info()

df.describe()

isnull = df.isnull()
isnull

sum_of_null = df.isnull().sum()
sum_of_null

drop_null = df.dropna()
drop_null

fill_0 = df.fillna("o")
fill_0

ffill = df.fillna(method='ffill')
ffill

bfill = df.fillna(method='bfill')
bfill

columns_to_fill = ['Credit_History', 'LoanAmount', 'Loan_Amount_Term']
df[columns_to_fill] = df[columns_to_fill].apply(lambda col: col.fillna(col.mean()))
df

df.dropna()
df

import pandas as pd
import seaborn as sns
import numpy as np

age=[1,3,28,27,25,92,30,39,40,50,26,24,29,94]
af=pd.DataFrame(age)
af

sns.boxplot(data = af)

Q1 = np.percentile(af, 25)
Q3 = np.percentile(af, 75)
IQR = Q3 - Q1
IQR

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

lower_bound

upper_bound

outliers = [x for x in age if x < lower_bound or x > upper_bound]
outliers

af = af[((af >= lower_bound) & (af <= upper_bound))]
af

af.dropna()

sns.boxplot(data = af)

from scipy import stats
import matplotlib.pyplot as plt

data = [1, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99, 158]
df = pd.DataFrame(data, columns=['Data'])
df

sns.boxplot(data=df, y='Data')
plt.show()

z_scores = stats.zscore(df['Data'])
outliers_z = df[(z_scores > 3) | (z_scores < -3)]
outliers_z

threshold = 3
df_clean = df[(z_scores < threshold) & (z_scores > -threshold)]
sns.boxplot(data=df_clean, y='Data')